### ISSUE TITLE
Frontend: Set up banner and button links

### ISSUE THREAD

**Issue by Leila-U** [Greenie-Beenie/Buy-Green-Website#19]
**Acceptance criteria:**
- The hyperlinks will be switched to nice buttons
- Non-copyright image and HD

Wireframes:
![image](https://user-images.githubusercontent.com/36177110/122281949-d8b55980-ceb8-11eb-964e-5648eb326707.png)

Example:
![image](https://user-images.githubusercontent.com/36177110/122281885-c9cea700-ceb8-11eb-8c6c-2ed890cc8e7b.png)

**Comment by mhasanat** [comment]
Does every page need to have that banner or is it just the home page?

**Comment by Leila-U** [comment]
> Does every page need to have that banner or is it just the home page?

The homepage is the only one that needs the banner. If we do need to use it for another page at least we have the banner component.
